

export const Teams = [
  {
    id: 'ne',
    name: 'New England Patriots',
    logo: '/logos/ne.svg',
    conference: 'AFC',
    division: 'East',
  },
  {
    id: 'mia',
    name: 'Miami Dolphins',
    logo: '/logos/mia.svg',
    conference: 'AFC',
    division: 'East',
  },
  {
    id: 'buf',
    name: 'Buffalo Bills',
    logo: '/logos/buf.svg',
    conference: 'AFC',
    division: 'East',
  },
  {
    id: 'nyj',
    name: 'New York Jets',
    logo: '/logos/nyj.svg',
    conference: 'AFC',
    division: 'East',
  },
  {
    id: 'bal',
    name: 'Baltimore Ravens',
    logo: '/logos/bal.svg',
    conference: 'AFC',
    division: 'North',
  },
  {
    id: 'cin',
    name: 'Cincinnati Bengals',
    logo: '/logos/cin.svg',
    conference: 'AFC',
    division: 'North',
  },
  {
    id: 'cle',
    name: 'Cleveland Browns',
    logo: '/logos/cle.svg',
    conference: 'AFC',
    division: 'North',
  },
  {
    id: 'pit',
    name: 'Pittsburgh Steelers',
    logo: '/logos/pit.svg',
    conference: 'AFC',
    division: 'North',
  },
  {
    id: 'hou',
    name: 'Houston Texans',
    logo: '/logos/hou.svg',
    conference: 'AFC',
    division: 'South',
  },
  {
    id: 'ind',
    name: 'Indianapolis Colts',
    logo: '/logos/ind.svg',
    conference: 'AFC',
    division: 'South',
  },
  {
    id: 'jax',
    name: 'Jacksonville Jaguars',
    logo: '/logos/jax.svg',
    conference: 'AFC',
    division: 'South',
  },
  {
    id: 'ten',
    name: 'Tennessee Titans',
    logo: '/logos/ten.svg',
    conference: 'AFC',
    division: 'South',
  },
  {
    id: 'den',
    name: 'Denver Broncos',
    logo: '/logos/den.svg',
    conference: 'AFC',
    division: 'West',
  },
  {
    id: 'kc',
    name: 'Kansas City Chiefs',
    logo: '/logos/kc.svg',
    conference: 'AFC',
    division: 'West',
  },
  {
    id: 'lv',
    name: 'Las Vegas Raiders',
    logo: '/logos/lv.svg',
    conference: 'AFC',
    division: 'West',
  },
  {
    id: 'lac',
    name: 'Los Angeles Chargers',
    logo: '/logos/lac.svg',
    conference: 'AFC',
    division: 'West',
  },
  {
    id: 'dal',
    name: 'Dallas Cowboys',
    logo: '/logos/dal.svg',
    conference: 'NFC',
    division: 'East',
  },
  {
    id: 'nyg',
    name: 'New York Giants',
    logo: '/logos/nyg.svg',
    conference: 'NFC',
    division: 'East',
  },
  {
    id: 'phi',
    name: 'Philadelphia Eagles',
    logo: '/logos/phi.svg',
    conference: 'NFC',
    division: 'East',
  },
  {
    id: 'was',
    name: 'Washington Commanders',
    logo: '/logos/was.svg',
    conference: 'NFC',
    division: 'East',
  },
  {
    id: 'chi',
    name: 'Chicago Bears',
    logo: '/logos/chi.svg',
    conference: 'NFC',
    division: 'North',
  },
  {
    id: 'det',
    name: 'Detroit Lions',
    logo: '/logos/det.svg',
    conference: 'NFC',
    division: 'North',
  },
  {
    id: 'gb',
    name: 'Green Bay Packers',
    logo: '/logos/gb.svg',
    conference: 'NFC',
    division: 'North',
  },
  {
    id: 'min',
    name: 'Minnesota Vikings',
    logo: '/logos/min.svg',
    conference: 'NFC',
    division: 'North',
  },
  {
    id: 'atl',
    name: 'Atlanta Falcons',
    logo: '/logos/atl.svg',
    conference: 'NFC',
    division: 'South',
  },
  {
    id: 'car',
    name: 'Carolina Panthers',
    logo: '/logos/car.svg',
    conference: 'NFC',
    division: 'South',
  },
  {
    id: 'no',
    name: 'New Orleans Saints',
    logo: '/logos/no.svg',
    conference: 'NFC',
    division: 'South',
  },
  {
    id: 'tb',
    name: 'Tampa Bay Buccaneers',
    logo: '/logos/tb.svg',
    conference: 'NFC',
    division: 'South',
  },
  {
    id: 'ari',
    name: 'Arizona Cardinals',
    logo: '/logos/ari.svg',
    conference: 'NFC',
    division: 'West',
  },
  {
    id: 'la',
    name: 'Los Angeles Rams',
    logo: '/logos/la.svg',
    conference: 'NFC',
    division: 'West',
  },
  {
    id: 'sf',
    name: 'San Francisco 49ers',
    logo: '/logos/sf.svg',
    conference: 'NFC',
    division: 'West',
  },
  {
    id: 'sea',
    name: 'Seattle Seahawks',
    logo: '/logos/sea.svg',
    conference: 'NFC',
    division: 'West',
  },
];








